image: opensuse/leap:latest

stages:
  - deploy

buildibs:
  stage: deploy
  before_script:
    - zypper in --no-confirm python-xml python2-packaging osc obs-service-tar_scm obs-service-recompress obs-service-set_version
    - mv "$SUSE_CA" /etc/pki/trust/anchors/SUSE_Trust_Root.pem && update-ca-certificates
    - mkdir -p /root/.config/osc && mv "$OSC_RC" /root/.config/osc/oscrc
  script:
    - cd $CI_PROJECT_DIR
    - osc co QA:Maintenance:Test mtui
    - cd QA:Maintenance:Test/mtui
    - rm -f *.tar.xz
    - osc service disabledrun
    - osc ar
    - osc ci -m "Automatic update"
  only:
    - master@qa-maintenance/mtui
