image: ibs:latest

test:
  script:
    - cd /builds/qa-maintenance/mtui
    - zypper ar -f http://download.suse.de/ibs/QA:/Maintenance/SLE_12_SP1/ QA:Maintenance
    - zypper install --no-confirm python-paramiko python-setuptools python-xdg repose rpm-python python-nose
    - make check
  tags:
    - qam
  only:
    - /^master.*$/
