include:
  - project: qa-maintenance/qamops
    file: /gitlab/templates.yml

variables:
  OSC_PACKAGE: mtui

test:
  stage: test
  before_script:
    - zypper ar http://download.suse.de/ibs/QA:/Maintenance/$OSC_REPO/QA:Maintenance.repo
    - zypper --gpg-auto-import-keys ref
    - >
      zypper in --no-confirm
      python3-openqa_client
      python3-paramiko
      python3-pytest
      python3-pyxdg
      python3-requests
      python3-responses
      python3-rpm
      python3-ruamel.yaml
      qam-metadata
      subversion
  script:
    - python3 -m pytest -v -k'not test_create_permission_denied'

publish_devel:
  extends: .obs:autoupdate
  variables:
    OSC_PROJECT: QA:Maintenance:Test
  rules:
    - if: $CI_PROJECT_NAMESPACE == "qa-maintenance" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
